name: Build & Upload Flutter Release to Google Drive

on:
  push:
    tags:
      - 'v*'  # كل مرة تعمل Tag زي v1.0.0 workflow يشتغل

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'  # غيّر حسب نسختك

      - name: Get dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Install rclone
        run: sudo apt-get update && sudo apt-get install -y rclone

      - name: Configure rclone
        run: |
          echo "${{ secrets.GDRIVE_CREDENTIALS }}" > client_secret.json
          rclone config create gdrive drive scope=drive.file service_account_file=client_secret.json

      - name: Upload APK to Google Drive
        run: |
          FOLDER_ID="1xymCLEQGwRQ1BSFnwjN"   # حط هنا الـ Folder ID بتاعك
          rclone copy build/app/outputs/flutter-apk/app-release.apk gdrive:${FOLDER_ID}
